---
title: "Recombinant Viral Concordance"
author: "Ian Zumpano"
date: "`r Sys.Date()`"
output:
  github_document:
    toc: true
    html_preview: false
  html_notebook:
    toc: true
    toc_float: true
---

```{r setup}
library(tidyverse)
library(ggplot2)
library(cowplot)
library(patchwork)
library(DESeq2)
library(ComplexHeatmap)
library(IHW)
library(RColorBrewer)
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
source("../functions/plotting_fxns.R")
theme_set(theme_Publication())
```

### [Import Data]{.underline}

```{r}
data <- read.csv("../processing_outs/count_matrix_umiDeDup_SIG06.csv", row.names = "X")

metadata <- read_csv("../processing_outs/processed_metadata_SIG06.csv")

# import feature names
featureNames <- read_csv("../processing_outs/featureNames_SIG06.csv")
featureNames <- select(featureNames, -category)
```

### [Normalization and Diagnostic Plots]{.underline}

```{r}
# prepare metadata for DESeq
metaDF <- as.data.frame(metadata[,-1])
rownames(metaDF) <- metadata$sample_ID

# match matrix and metadata
data <- data[,rownames(metaDF)]
```

#### Read normalized counts

```{r}
normCounts <- read.csv("../analysis_outs/counts_norm_DEseq2.csv")

dds_norm <- vst(dds)
```

#### Create DESeq object

```{r}
# import dds object
dds <- readRDS("/Users/izumpano/Desktop/Eric Analyses/SIG06/analysis_outs/dds_object_SIG06.rds")
```

#### Create Treatment Groups 

```{r}
# select viral treatments groups
viralGroups <- dds$treatment %>% unique()
viralGroups <- viralGroups[grep("recomb|none|linker", viralGroups, invert = T)]
viralGroups
```

```{r}
# select recombinant treatments groups
recombGroups <- dds$treatment %>% unique()
recombGroups <- grep("recomb", recombGroups, value = T)
recombGroups
```

```{r}
# select linkers
linkerGroups <- dds$treatment %>% unique()
linkerGroups <- grep("linker", linkerGroups, value = T)
linkerGroups
```

### Load DEG Analysis

```{r}
res_viral <- read.csv("../analysis_outs/res_viral.csv")
res_recomb <- read.csv("../analysis_outs/res_recomb_vs_none.csv")
```

### DE Genes Analysis

```{r}
find_DE_concordance_all_pairs <- function(df1, df2, padj_threshold = 0.1) {
  # Extract unique treatments
  treatments_viral <- unique(df1$treatment)
  treatments_recomb <- unique(df2$treatment)
  
  # Match treatments (assumes `recomb` treatments are `viral` + "recomb")
  treatment_pairs <- lapply(treatments_viral, function(viral_treatment) {
    recomb_treatment <- paste0(viral_treatment, "recomb")
    if (recomb_treatment %in% treatments_recomb) {
      return(c(viral = viral_treatment, recomb = recomb_treatment))
    } else {
      return(NULL)
    }
  })
  
  # Filter non-matching treatments
  treatment_pairs <- Filter(Negate(is.null), treatment_pairs)
  
  # Initialize results list
  results_list <- list()
  
  # Loop through matched treatment pairs
  for (pair in treatment_pairs) {
    viral_treatment <- pair["viral"]
    recomb_treatment <- pair["recomb"]
    
    # Subset data for each treatment
    df1_subset <- df1[df1$treatment == viral_treatment, ]
    df2_subset <- df2[df2$treatment == recomb_treatment, ]
    
    # Identify DEGs in each dataset
    DE_genes_viral <- df1_subset$ensembl_ID[df1_subset$padj <= padj_threshold]
    DE_genes_recomb <- df2_subset$ensembl_ID[df2_subset$padj <= padj_threshold]
    
    # Find overlapping DEGs
    common_genes <- intersect(DE_genes_viral, DE_genes_recomb)
    
    # Find unique DEGs
    unique_genes_viral <- setdiff(DE_genes_viral, DE_genes_recomb)
    unique_genes_recomb <- setdiff(DE_genes_recomb, DE_genes_viral)
    
    # Save results for this pair
    results_list[[paste(viral_treatment, "vs", recomb_treatment, sep = "_")]] <- list(
      num_DE_viral = length(DE_genes_viral),
      num_DE_recomb = length(DE_genes_recomb),
      num_common_DE = length(common_genes),
      genes_common = common_genes,
      genes_unique_viral = unique_genes_viral,
      genes_unique_recomb = unique_genes_recomb
    )
  }
  
  return(results_list)
}

results <- find_DE_concordance_all_pairs(res_viral, res_recomb, padj_threshold = 0.1)

# Example: Access results for `IL2` vs `IL2recomb`
results[["IL2_vs_IL2recomb"]]
```

#### Plot Venn Diagrams of DEGs

```{r, fig.width = 8, fig.height=6}
library(ggVennDiagram)
library(RColorBrewer)

# Plot Venn diagrams for each treatment pair
for (pair_name in names(results)) {
  # Get data for the pair
  pair_data <- results[[pair_name]]
  
  # Create a list of DEGs for Venn diagram
  gene_lists <- list(
    Viral = pair_data$genes_unique_viral,
    Recombinant = pair_data$genes_unique_recomb,
    Common = pair_data$genes_common
  )
  
  # Combine unique and common DEGs
  combined_lists <- list(
    Viral = unique(c(pair_data$genes_unique_viral, pair_data$genes_common)),
    Recombinant = unique(c(pair_data$genes_unique_recomb, pair_data$genes_common))
  )
  
  # Generate and plot the Venn diagram
  print(ggVennDiagram(combined_lists, category.names = c("Viral", "Recombinant"), label_size = 6) +
          ggtitle(paste("Venn Diagram for", pair_name)) +
          theme(plot.title = element_text(hjust = 0.5)) +
          coord_flip() 
        )
}
```

