---
title: "UMAP and Clustering"
author: "Ian Zumpano"
date: "`r Sys.Date()`"
output:
  github_document:
    toc: true
    html_preview: false
  html_notebook:
    toc: true
    toc_float: true
---

```{r setup}
library(tidyverse)
library(ggplot2)
library(cowplot)
library(patchwork)
library(DESeq2)
library(ComplexHeatmap)
library(IHW)
library(RColorBrewer)
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
source("../functions/plotting_fxns.R")
theme_set(theme_Publication())
```

### [Import Data]{.underline}

```{r}
data <- read.csv("../processing_outs/count_matrix_umiDeDup_SIG06.csv", row.names = "X")

metadata <- read_csv("../processing_outs/processed_metadata_SIG06.csv")

# import feature names
featureNames <- read_csv("../processing_outs/featureNames_SIG06.csv")
featureNames <- select(featureNames, -category)
```

### [Normalization and Diagnostic Plots]{.underline}

```{r}
# prepare metadata for DESeq
metaDF <- as.data.frame(metadata[,-1])
rownames(metaDF) <- metadata$sample_ID

# match matrix and metadata
data <- data[,rownames(metaDF)]
```

#### Read normalized counts

```{r}
normCounts <- read.csv("../analysis_outs/counts_norm_DEseq2.csv")
```

#### Create DESeq object

```{r}
# import dds object
dds <- readRDS("/Users/izumpano/Desktop/Eric Analyses/SIG06/analysis_outs/dds_object_SIG06.rds")
```

#### Create Treatment Groups 

```{r}
# select viral treatments groups
viralGroups <- dds$treatment %>% unique()
viralGroups <- viralGroups[grep("recomb|none|linker", viralGroups, invert = T)]
viralGroups
```

```{r}
# select recombinant treatments groups
recombGroups <- dds$treatment %>% unique()
recombGroups <- grep("recomb", recombGroups, value = T)
recombGroups
```

```{r}
# select linkers
linkerGroups <- dds$treatment %>% unique()
linkerGroups <- grep("linker", linkerGroups, value = T)
linkerGroups
```

### Load DEG Analysis

```{r}
res_viral <- read.csv("../analysis_outs/res_viral.csv")
```

### UMAP Analysis

#### Perform UMAP

```{r}
library(umap)

dds_norm <- vst(dds)

# First we are going to retrieve the normalized data
# from the `DESeqDataSet` object using the `assay()` function
normalized_counts_umap <- assay(dds_norm) %>%
  t() # We need to transpose this data so each row is a sample

# Now perform UMAP on the normalized data
umap_results <- umap::umap(normalized_counts_umap)
```

#### Prepare data frame for plotting

```{r}
# Make into data frame for plotting with `ggplot2`
# The UMAP values we need for plotting are stored in the `layout` element
umap_plot_df <- data.frame(umap_results$layout) %>%
  # Turn sample IDs stored as row names into a column
  tibble::rownames_to_column("sample_ID") %>%
  # Add the metadata into this data frame; match by sample IDs
  dplyr::inner_join(metadata, by = "sample_ID")


#Create Well to row col dataset
umap_plot_df_well_rowcol <- umap_plot_df %>%
  mutate(
    well_row = sub("\\d+", "", well),       # Extract the letter (row)
    well_column = as.numeric(sub("\\D+", "", well)) # Extract the number (column)
  )

```

#### Create UMAP Plots

```{r, fig.height=10, fig.width=12}
library(ggrepel)
library(patchwork)

p1 <- ggplot(umap_plot_df, aes(x = X1, y = X2, color = replicate)) +
  geom_point(shape = 15) + 
  labs(title="UMAP by Group")

p2 <- ggplot(umap_plot_df, aes(x = X1, y = X2, color = plate)) +
  geom_point(shape = 15) + 
  labs(title="UMAP by RNA-seq Plate")

p3 <- ggplot(umap_plot_df_well_rowcol, aes(x = X1, y = X2, color = well_row)) +
  geom_point(shape = 15) + 
  labs(title="UMAP by Row")

p4 <- ggplot(umap_plot_df_well_rowcol, aes(x = X1, y = X2, color = factor(well_column))) +
  geom_point(shape = 15) + 
  labs(title="UMAP by Column")

p5 <- ggplot(umap_plot_df_well_rowcol, aes(x = X1, y = X2, color = factor(treatment))) +
  geom_point(shape = 15) + 
  labs(title="UMAP by Treatment")



p1+p2+p3+p4+plot_layout(ncol=2)
# highlight which cells are the linker only cells
# run a clustering algorithm on data to identify discrete clusters, then project clusters onto the umap to see which ligands are enriched clusters
# simple heirarchical clustering
```

```{r, fig.height= 12, fig.width= 18}
p5
```


### Run Clustering Analysis

```{r, fig.width=24, fig.height=30}
library(ggdendro)

hc <-  normalized_counts_umap %>%
   dist(method = "euclidean") %>%
   hclust()

ggdendrogram(hc, rotate=TRUE)

#add in metadata
hc_meta <- hc
hc_meta$labels <- str_c(metadata$treatment, ":", metadata$nCount_RNA)
ggdendrogram(hc_meta, rotate=TRUE)

```

### Overlay Clustering on UMAP

```{r}
dark2_pal <- brewer.pal(8, "Dark2")

# Define the number of clusters
num_clusters <- 5
clusters <- cutree(hc, k = num_clusters)
clusters_meta <- cutree(hc_meta, k = num_clusters)

umap_cluster <- umap_plot_df
umap_cluster$cluster <- as.factor(clusters)  # Add the cluster assignments to UMAP results

umap_cluster$cluster_meta <- as.factor(clusters_meta)

# Plot UMAP with clusters
ggplot(umap_cluster, aes(x = X1, y = X2, color = cluster)) +
  geom_point(size = 2, shape = 15) +
  labs(title = "UMAP Projection with Hierarchical Clusters", x = "UMAP 1", y = "UMAP 2") +
  theme_minimal() +
  scale_color_manual(values = c("salmon", "navyblue", "seagreen", "darkgoldenrod1", "darkorchid")) 

# Plot UMAP with clusters
ggplot(umap_cluster, aes(x = X1, y = X2, color = cluster_meta)) +
  geom_point(size = 2, shape = 15) +
  labs(title = "UMAP Projection with Hierarchical Clusters (Metadata)", x = "UMAP 1", y = "UMAP 2") +
  theme_minimal() +
  scale_color_manual(values = c("salmon", "navyblue", "seagreen", "darkgoldenrod1", "darkorchid")) 


# try overlaying ligands onto umap
# take a closer look at PCs, some ligands that have strong signalling effect, look at pcas only on genes that dont have strong DEGs (null genes subset), might reveal what is driving batch effect more
# minimal distortion embedding
# focus on 2 and 4, try to figure out what covars are driving variation
# want to see how mych overlap genes that are DE between viral and DE for recomb

# for 2, make seperate notebook
```

```{r}
# Non DE Genes

null_genes <- res_viral %>% filter(padj > 0.2) %>% pull(ensembl_ID)

dds_norm[null_genes, ]
```

