---
title: "DEG Analysis"
author: "Ian Zumpano"
date: "`r Sys.Date()`"
output:
  github_document:
    toc: true
    html_preview: false
  html_notebook:
    toc: true
    toc_float: true
---

```{r setup}
library(tidyverse)
library(ggplot2)
library(cowplot)
library(patchwork)
library(DESeq2)
library(ComplexHeatmap)
library(IHW)
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
source("../functions/plotting_fxns.R")
theme_set(theme_Publication())
```

### [Import Data]{.underline}

```{r}
data <- read.csv("../processing_outs/count_matrix_umiDeDup_SIG06.csv", row.names = "X")

metadata <- read_csv("../processing_outs/processed_metadata_SIG06.csv")

# import feature names
featureNames <- read_csv("../processing_outs/featureNames_SIG06.csv")
featureNames <- select(featureNames, -category)
```

### [Normalization and Diagnostic Plots]{.underline}

```{r}
# prepare metadata for DESeq
metaDF <- as.data.frame(metadata[,-1])
rownames(metaDF) <- metadata$sample_ID

# match matrix and metadata
data <- data[,rownames(metaDF)]
```

```{r}
# # create DEseq object
# dds <- DESeqDataSetFromMatrix(data,
#                               colData = metaDF,
#                               design = ~ treatment + replicate)
# 
# # prefilter dds
# # remove any gene with fewer than 5 counts in the smallest group size
# smallestGroupSize <- 3
# keep <- rowSums(counts(dds) >= 2) >= smallestGroupSize
# dds <- dds[keep,]
```

#### Read normalized counts

```{r}
# dds <- estimateSizeFactors(dds)
```

```{r}
# normCounts <- counts(dds, normalized=T) %>%
#   as_tibble(rownames = "ensembl_ID") %>%
#   left_join(featureNames)
# 
# write_csv(normCounts, "../analysis_outs/counts_norm_DEseq2.csv")

normCounts <- read.csv("../analysis_outs/counts_norm_DEseq2.csv")
```

### [DEG Analysis]{.underline}

#### Create DESeq object

```{r}
# # perform DE analysis
# dds <- DESeq(dds, parallel = TRUE)
```

```{r}
# # save dds object
# saveRDS(dds, "analysis_outs/dds_object_SIG07.rds")

# import dds object
dds <- readRDS("/Users/izumpano/Desktop/Eric Analyses/SIG06/analysis_outs/dds_object_SIG06.rds")
```

#### Calculate DEGs

Made a quick helper function to calculate DEGs.
```{r}
# library(IHW)
# library(BiocParallel)
# 
# #Configure the amount of cores used (mac/linux specific function)
# # cores <- MulticoreParam(workers = 8) #8 cores
# 
# # import feature names (used in function below)
# featureNames <- read_csv("../processing_outs/featureNames_SIG06.csv")
# featureNames <- select(featureNames, -category)
# 
# # sample input can be single character or vector of characters
# # control input must be single character, defaults to linker
# iterative_DEG <- function(samples, control = "linker"){
#   # empty tibble for full DEG list
#   resAll <- tibble()
#   for(ligand in samples){
#     print(ligand)
#     # perform IHW DEG analysis
#     # don't perform independent filtering because using IHW
#     res <- results(dds, contrast = c("treatment",ligand,control),
#                  independentFiltering=F,
#                  filterFun = ihw,
#                  parallel = T)
#                  #BPPARAM = cores 
#     
#     # perform LFC shrinkage and make tidy
#     # pass res to lfcShrink
#     resTidy <- lfcShrink(dds, type = "ashr", res=res) %>%
#       as_tibble(rownames = "ensembl_ID") %>%
#       left_join(featureNames) %>%
#       mutate(treatment = ligand) %>%
#       arrange(padj)
#     
#     # add to full DEG list
#     resAll <- bind_rows(resAll, resTidy)
#   }
#   return(resAll)
# }
```

```{r}
iterative_DEG <- function(samples, control = "linker") {
  # Empty tibble for full DEG list
  resAll <- tibble()
  
  # Iterate through ligands in samples
  for (ligand in samples) {
    
    # Perform IHW DEG analysis
    res <- results(
      dds,
      contrast = c("treatment", ligand, control),
      independentFiltering = FALSE,
      filterFun = ihw,
      parallel = TRUE
    )
    
    # Perform LFC shrinkage
    resTidy <- lfcShrink(dds, type = "ashr", res = res) %>%
      as_tibble(rownames = "ensembl_ID") %>%
      left_join(featureNames, by = "ensembl_ID") %>%
      mutate(treatment = ligand) %>%
      arrange(padj)
    
    # Append results to cumulative tibble
    resAll <- bind_rows(resAll, resTidy)
  }
  
  return(resAll)
}
```


#### Create Treatment Groups 

```{r}
# select viral treatments groups
viralGroups <- dds$treatment %>% unique()
viralGroups <- viralGroups[grep("recomb|none|linker", viralGroups, invert = T)]
viralGroups
```

```{r}
# select recombinant treatments groups
recombGroups <- dds$treatment %>% unique()
recombGroups <- grep("recomb", recombGroups, value = T)
recombGroups
```

```{r}
# select linkers
linkerGroups <- dds$treatment %>% unique()
linkerGroups <- grep("linker", linkerGroups, value = T)
linkerGroups
```

### Run DEG Analysis

```{r}
# res_viral <- iterative_DEG(viralGroups)
# write_csv(res_viral, "../analysis_outs/res_viral.csv")
# 
# res_recomb_vs_none <- iterative_DEG(recombGroups, "none")
# write_csv(res_recomb_vs_none, "../analysis_outs/res_recomb_vs_none.csv")
# 
# res_linker_vs_none <- iterative_DEG(linkerGroups, "none")
# write_csv(res_linker_vs_none, "../analysis_outs/res_linker_vs_none.csv")
```

```{r}
res_viral <- read.csv("../analysis_outs/res_viral.csv")
```


### Count and Visualize DEGs per Treatment

#### Count DEGs per Treatment

```{r}
res_viral <-  read.csv("../analysis_outs/res_viral.csv")

# Define significance threshold
significant_padj_threshold <- 0.1

# Count DEGs for each treatment, including treatments with zero DEGs
deg_count <- res_viral %>%
  filter(padj < significant_padj_threshold) %>%
  group_by(treatment) %>%
  summarize(DEG_count = n(), .groups = "drop") %>%
  complete(treatment = viralGroups, fill = list(DEG_count = 0)) %>%   # Fill missing treatments with 0
  arrange(desc(DEG_count))
  
res_viral_sig <- res_viral %>%
  filter(padj < significant_padj_threshold)

write_csv(res_viral_sig, "../analysis_outs/res_viral_sig.csv")

print(deg_count)
```

#### Barplot of DEGs per Treatment

```{r}
library(ggplot2)

ggplot(deg_count, aes(x = treatment, y = DEG_count, fill = treatment)) +
  geom_bar(stat = "identity", show.legend = FALSE) +
  labs(title = "Number of DEGs per Treatment", x = "Treatment", y = "DEG Count") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```